NUM_WORKER_NODES=2

#ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    echo "172.42.42.100 kmaster.example.com kmaster" >> /etc/hosts
    echo "172.42.42.101 kworker1.example.com kworker1" >> /etc/hosts
    echo "172.42.42.102 kworker2.example.com kworker2" >> /etc/hosts
  SHELL

  # https://app.vagrantup.com/ubuntu/boxes/focal64
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = true

  config.vm.define "master" do |master|
    # master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "kmaster.example.com"
    master.vm.network "private_network", ip: "172.42.42.100"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "kmaster"
      vb.memory = 4096
      vb.cpus = 4
    end
    master.vm.provision "shell", path: "scripts/common.sh"
    master.vm.provision "shell", path: "scripts/master.sh"
  end

  (1..NUM_WORKER_NODES).each do |i|
    config.vm.define "node0#{i}" do |node|
      node.vm.hostname = "kworker#{i}.example.com"
      node.vm.network "private_network", ip: "172.42.42.10#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "kworker#{i}"
        vb.memory = 6144
        vb.cpus = 2
      end
      node.vm.provision "shell", path: "scripts/common.sh"
      node.vm.provision "shell", path: "scripts/node.sh"
    end
  end
end
